on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Commit package-lock.json if not existing
        env:
          GITHUB_TOKEN: ${{ secrets.GT }}
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json already exists."
          else
            echo "package-lock.json does not exist. Generating..."
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add package-lock.json
            git commit -m "Add missing package-lock.json"
            git push
          fi
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: |
#          sudo cp kubectl /usr/local/bin
#          sudo chmod 755 /usr/local/bin/kubectl
      - uses: ./
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"   # replace your project_id
          cluster_id: "8817579e-f98a-11ee-990c-0255ac1000eb"    # replace your cluster_id
      - run: |
          kubectl version --client
          kubectl config view
          kubectl cluster-info
          kubectl get pod,svc --all-namespaces
